#Um dicionário é uma estrutura de dados que armazena pares chaves-valor. É muito útil qaundo queremos associar uma informação (valor) a uma etiqueta única (chave).
#exemplo
aluno={'nome':"joão", 'idade': 20,'curso':'ADS'}
print(f'O nome do aluno é {aluno['nome']}')
print(f'A idade do aluno é {aluno['idade']}')
print(f'O curso do aluno é {aluno[f'curso']}')

# a sintaxe para criar um dicionario é (d={'chave':'valor'})